name: Export to PDF

on:
  release:
    types: [published]

  workflow_dispatch: ~

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Update pip
      run: pip install -U pip

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Build PDF
      run: make latexpdf

    - name: Store artifacts
      uses: actions/upload-artifact@v1
      with:
        name: doc-pdfs
        path: build
